### ISSUE TITLE
关于自定义表单

### ISSUE THREAD

**Issue by wgd33952** [nangge/noneCms#1]
企业站或博客中，还有一个比较基础的功能就是自定义表单吧~ 例如一些联系商家的表单

**Comment by nangge** [comment]
你意思就是留言板吧！
这个功能可以有，下一小版本将会上。
谢谢你提的意见哈 :)

**Comment by wgd33952** [comment]
其实还想请教，如果想增加一个banner的管理，该怎么增加会比较方便呢

**Comment by wendy-rose** [comment]
我发现安装后系统没有办法用，里面的导航链接点击没有用，我看了一下，你没有隐藏入口文件导致会这样
