### ISSUE TITLE
分页使用

### ISSUE THREAD

**Issue by king192** [nangge/noneCms#3]
看了好久
article 示例：
```
{article orderby="publishtime DESC" pagesize='15'}
//CODE...
{/article}
参数：cid, // 栏目ID
field, // 指定要取的字段
orderby, // 排序规则
limit, // 限制条数
pagesize // 分页 （pagesize 和 limit 只能选一个）
```
1.使用limit（则不用pagesize），调用完article标签后{$list->render()}
2.使用pagesize（则不用limit），调用完后直接用{$page}

**Comment by nangge** [comment]
你的表述不太清楚，上个问题也是。
根据字面：
首先`$list->render()`是进行页数渲染；如果用`article`标签并且使用`pagesize`进行分页的话，这里的`{$page}`就是经过简单封装的`{$list->render()}`；如果调用了‘limit’属性，则不存在`{$page}和{$list->render()}`

**Comment by king192** [comment]
[http://pan.baidu.com/s/1pKRBgjL](http://pan.baidu.com/s/1pKRBgjL)

**Comment by nangge** [comment]
`
 \$list = think\Db::name('article')->where(\$condition);
    if(isset(\$children_ids) && \$children_ids){
         \$list = \$list->whereor('cid','in',\$children_ids);
     }

    if("$field" != ''){
        \$list=\$list->field("$field");
    }

    if("$order" != ''){
        \$list=\$list->order("$order");
    }

    if($pagesize > 0){
        \$list=\$list->paginate($pagesize);
        \$page = \$list->render();
    }else{
        if($limit != 0){
            \$list=\$list->limit($limit);
        }
        \$list=\$list->select();

    }
`
给你附上一段‘article’的源码吧。可以看到‘ \$page = \$list->render();’，而你之所有可以直接用‘{$list->render()}’，那是因为我声明的结果集变量也是‘$list’.
