### ISSUE TITLE
json封装

### ISSUE THREAD

**Issue by king192** [nangge/noneCms#4]
前后端交互的json返回封装一下会更简洁
代码：
exit(json_encode(['status' => 0, 'msg' => '更新失败，请稍后重试', 'url' => '']));
封装：
/**
 * json返回
 * @param  int $status over 0:success,under or equal 0:fail
 * @param  string $msg    msg
 * @param  string $data   data
 * @param  string $url    redirct url
 * @return json         [description]
 */
function json_rtn($status,$msg,$data=null,$url=null){
    exit(json_encode(['status' => $status, 'msg' => $msg, 'data'=>$data,'url' => $url]));
}
使用示例：
json_rtn(0,'更新失败，请稍后重试');

**Comment by nangge** [comment]
嗯，TP5是提供的有`json()`这个用于JSON数据输出的助手函数，只不过我没用使用 。。。也谢谢你的建议
