### ISSUE TITLE
修复bug一枚

### ISSUE THREAD

**Issue by king192** [nangge/noneCms#6]
- 位置：index/show/index

- 代码：

`<?php
namespace app\index\controller;

use think\Db;
use think\View;

class Show extends Common
{
    public function index()
    {
        $cid = input('param.cid');//栏目id
        $id = input('param.id');//资源id

        //根据cid来获取表模型
        $cat_info = Db::table($this->prefix . 'category cat,'.$this->prefix . 'model mo')
            ->where('cat.modelid = mo.id')
            ->where('cat.id', $cid)
            ->find();
        //获取资源内容
        $data = Db::name($cat_info['tablename'])->find($id);
        Db::name($cat_info['tablename'])->where('id',$id)->setInc('click');//点击+1

        //图片处理
        if(isset($data['pictureurls'])){
            $data['pictureurls'] = explode('|',$data['pictureurls']);
        }
        //获取模板文件
        $template_show = $cat_info['template_show'];

        if(!$template_show) {
            $model = Db::name('model')->field('template_show')->find($cat_info['modelid']);
            $template_show = $model['template_show'];
        }
        $template = 'template/index/'. $this->theme .'/'.$template_show;
        $this->assign('content',$data);
        $this->assign('title',$data['title']);
        $this->assign('keywords',$data['keywords']);
        $this->assign('description',$data['description']);
        $this->assign('cate',$cat_info);
        $this->assign('id',$id);
        $this->assign('cid',$cid);
        return $this->fetch($template);
    }

}

`

# bug:

使用{position /}时由于sql查询相同字段覆盖（id被覆盖），导致id不是category的id，而是modelid的id。

# 修改：

        $cat_info = Db::table($this->prefix . 'model mo,'.$this->prefix . 'category cat')

# 说明：仅解决id的问题，暂时没发现其他冲突（可能有其他冲突）

**Comment by nangge** [comment]
已修复 谢谢。
