### ISSUE TITLE
严重bug

### ISSUE THREAD

**Issue by king192** [nangge/noneCms#7]
后台图像上传没有验证
namespace app\admin\controller;
Main.php->upload()
** 代码：
$info = $file->move(ROOT_PATH . 'public/uploads');
** 修为
$info = $file->validate(['size'=>15678,'ext'=>'jpg,png,gif'])->move(ROOT_PATH . 'public/uploads');

** uploadEditor一样

**Comment by king192** [comment]
这个可以上传个php文件，分分钟黑掉系统

**Comment by nangge** [comment]
嗯，已经修复。
不过当时没看到`validate`方法，还是存在一定隐患。
这个`validate`方法应该是不错的，谢谢。
